---
title: "Bicep Curls"
author: "Ronny Restrepo"
date: "21/05/2015"
output: html_document
---


```{r setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE, tidy = FALSE}
# make this an external chunk that can be included in any file
library(knitr)
opts_chunk$set(message = F, error = F, warning = F, comment = NA, 
               fig.align = 'center', dpi = 100, tidy = F, 
               cache.path = '.cache/', cache=TRUE, 
               fig.path = 'fig/', fig.height=3, fig.width=4)

options(xtable.type = 'html')

knit_hooks$set(inline = function(x) {
  if(is.numeric(x)) {
    round(x, getOption('digits'))
  } else {
    paste(as.character(x), collapse = ', ')
  }
})
knit_hooks$set(plot = knitr:::hook_plot_html)
```



# TIPS
- use `doParallel`
- `readRDS()` and `saveRDS()` for caching R objects such as the trained data. 
-  use variable Importance `varImp()` function on the trained model. It shows the most important variables. 

``` {r cacheDownload, echo=FALSE}
#===============================================================================
#                                                                 CACHE DOWNLOAD
#===============================================================================
#' cacheDownload
#' 
#' Downloads a file from the internet, and caches it locally. 
#' 
#' Something
#' 
#' @param url (string) the URL to download from
#' @param dataDirectory (string) The directory where the local data will be 
#'        stored in
#' @param fileNameLocal (string) The name you want the file to be called locally
#' 
cacheDownload <- function(url, dataDirectory, fileNameLocal){
    # TODO: include option to override existing local file, eg, if there may be 
    #       reason to believe that the data has changed. 
    
    localPathToFile = paste(dataDirectory, fileNameLocal, sep="/")
    
    #---------------------------------------------------------------------------
    #                     Create a new data directory if it doesnt already exist
    #---------------------------------------------------------------------------
    if(!file.exists(dataDirectory)){
        message("Creating a new data directory '", dataDirectory, "'")
        dir.create(dataDirectory)
    }
     
    #---------------------------------------------------------------------------
    #                   Download a CSV file if it hasn't already been downloaded
    #---------------------------------------------------------------------------
    if(file.exists(localPathToFile)){
        dateDownloaded <- NA    # TODO: Load a datestamp from a file, so that it
                                # can be loaded up on start up
        message("Using existing ", localPathToFile, " file downloaded on ",
                dateDownloaded)
    } else {
        message("Downloading and saving data as ", localPathToFile)
        download.file(url, destfile=localPathToFile, method="curl")
        # Create a datestamp of the time the download was made
        dateDownloaded <- date()
        message("Download made on ", dateDownloaded)
        message("TODO: save the datestamp as a file, so it can be loaded up next",
                "time the script is run")
    }
}
```

```{r}
trainURL = "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
testURL = "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

cacheDownload(trainURL, "data", "trainData")
cacheDownload(testURL, "data", "testData")
```






```{r}
answers = rep("A", 20)
#answers = c("A", "B", "A", "C", "A", "B", "A", "C", "A")

#then you can load this function by copying and pasting it into R:
 
pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("answers/","problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}
#then create a folder where you want the files to be written. 
# Set that to be your working directory and run:
 
pml_write_files(answers)
```


